### ISSUE TITLE
Classic UI on QNAP not working

### ISSUE THREAD

**Issue by maikbooehme** [openhab/openhab-qnap-qpkg#34]
hi all, my classic UI is not working at all. Any idea why ? I believe it has something to do with my share and folder structure. my share is called "openHAB" and all folders from the installation are in there. The folder "openHAB2" recommended by the documentation is empty.

I believe the demo.sitemap is search in a wrong folder.

What did I wrong ?

HTTP ERROR 500

Problem accessing /classicui/app. Reason:

    Server Error
Caused by:

javax.servlet.ServletException: Sitemap 'demo.sitemap' could not be found
	at org.eclipse.smarthome.ui.classic.internal.servlet.WebAppServlet.service(WebAppServlet.java:165)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:71)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:287)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:80)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.eclipse.smarthome.ui.classic.render.RenderException: Sitemap 'demo.sitemap' could not be found
	at org.eclipse.smarthome.ui.classic.internal.servlet.WebAppServlet.service(WebAppServlet.java:130)
	... 21 more
Caused by:

org.eclipse.smarthome.ui.classic.render.RenderException: Sitemap 'demo.sitemap' could not be found
	at org.eclipse.smarthome.ui.classic.internal.servlet.WebAppServlet.service(WebAppServlet.java:130)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:71)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:287)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:80)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Andy1402** [comment]
Hi @maikbooehme.
Is the sitemap "demo" really existing in your OpenHAB Configuration?
If the file "demo.sitemap" really exists in your folder \OpenHAB\conf\sitemaps you should be able reach this sitemap with the URL:
http://YOUR-QNAP:8090/classicui/app?sitemap=demo

You wrote that your folder is empty. Is it really empty or maybe you have a problem with the symlink or the permissions in the file system. You can set the permissions on this way for example:
Login on your QNAP-NAS, go to:
Control Panel -> Shared Folders
Choose your OpenHAB folder an click on the 2. Action Icon on the right side (Edit Share Folder Permission)
Active the last checkbox "Apply and replace all existing permissions of this folder, files and subfolders" and press the Apply button. It will take some seconds...

If you want to check is the symlink from the shared folder is linked to the correct path, you can click on the first action Icon. In my case the path is /.qpkg/openHAB

Regards.
Andy

**Comment by maikbooehme** [comment]
hi Andy, I believe the ClassicUI is searching in a differnt folder for the config as the BasicUI .
But sofar I'm not able to isolate the issue. I'm currently installing your QPKG 2.2.0 . 

Lets see whats happening afterwards :-)

**Comment by 6r15u** [comment]
@maikbooehme : Any Update here? Or problem solved
