### ISSUE TITLE
OpenHAB not working after Firmware update QNAP NAS

### ISSUE THREAD

**Issue by todtzynsky** [openhab/openhab-qnap-qpkg#46]
Hello,

After updating the firmware of my QNAP TS 253, OpenHAB is not reachable anymore.  I tried to solve this by re-installing the package, but the result remains the same.
Has anybody ideas how to solve this ?

Regards,

Marc

**Comment by 6r15u** [comment]
Did you check if java is installed correctly?

**Comment by justincredible68** [comment]
I have tried to install it for the first time on my QNAP. At first  I was able to get to the configuration web page, but that only lasted for a few minutes, and not I cannot access the page. I have tried to uninstall and reinstall, and restart the NAS with no luck.

And Java is installed.

**Comment by Alecdo-Attis** [comment]
I had the same issue. OpenHAB worked well and stopped after the latest firm-ware upate of the QNAP-NAS. I had not only to delete the Openhab-App but as well to delete the three folders in the OpenHAB folder (!) and let OpenHAB establish them again with the re-installation of the app. Did then copy/paste my files (items, rules etc.) from a backup into the three folders and all is back to normal again.
Only reinstalling the OpenHAB app without deleting the three folders did not work for me and gave me the same error message as @todtzynsky.

**Comment by YeouWei** [comment]
I think there's a problem on restarting OH after the NAS is restarted for any reason. My NAS is scheduled to restart once every week. After restarting, OH will fail to work. After reading through so many threads and trying so many different approaches, I found that the only approach that works is deleting the three folders and reinstalling. 

Anyways, below is excerpt from my openhab.log file:
`2018-04-02 12:29:08.265 [ERROR] [io.openhabcloud.internal.CloudClient] - Socket.IO error: {}`
`io.socket.engineio.client.EngineIOException: xhr poll error`
`	at io.socket.engineio.client.Transport.onError(Transport.java:71) [202:org.openhab.io.openhabcloud:2.2.0]`
`	at io.socket.engineio.client.transports.PollingXHR.access$100(PollingXHR.java:19) [202:org.openhab.io.openhabcloud:2.2.0]`
`	at io.socket.engineio.client.transports.PollingXHR$6$1.run(PollingXHR.java:124) [202:org.openhab.io.openhabcloud:2.2.0]`
`	at io.socket.thread.EventThread$2.run(EventThread.java:80) [202:org.openhab.io.openhabcloud:2.2.0]`
`	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]`
`	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]`
`	at java.lang.Thread.run(Thread.java:748) [?:?]`
`Caused by: java.io.IOException: 502`
`	at io.socket.engineio.client.transports.PollingXHR$Request$1.run(PollingXHR.java:218) ~[?:?]`
`	... 1 more`

**Comment by jonadem** [comment]
I had the same issue after an firmware update to 4.3.3.0514
Re-installation didn't help. I had to re-install with the deletion of the 3 folders to have it back.
