### ISSUE TITLE
Problem accessing /start/index. Reason: Not Found

### ISSUE THREAD

**Issue by nodecentral** [openhab/openhab-qnap-qpkg#7]
Hi

After successfully installing openHAB_2.0.0-b4-2.qpkg on another NAS (TS453 Pro) , when I try to open it I get the following error message when trying either https://192.168.1.111:8444/start/index or http://192.168.1.111:8090/start/index

**HTTP ERROR 404**

Problem accessing /start/index. Reason:

    Not Found

Powered by Jetty://

**Comment by nodecentral** [comment]
I've tried to remove and reinstall, but still get the same thing..

The openhab.log file looks very large, with a numerous errors listed; such as

----
2016-11-13 20:56:08.619 [ERROR] [org.apache.felix.configadmin        ] - Configuration org.apache.felix.fileinstall.5b33c608-689a-4744-b192-b6721c9ea33b referred to by factory org.apache.felix.fileinstall does not exist
2016-11-13 20:56:24.185 [ERROR] [.glassfish.hk2.osgi-resource-locator] - FrameworkEvent ERROR - org.glassfish.hk2.osgi-resource-locator
----- 
2016-11-13 20:56:37.553 [WARN ] [org.apache.karaf.shell.ssh.Activator] - Exception caught while starting SSH server
java.net.BindException: Address already in use
-----
2016-11-13 20:57:10.867 [ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-package-standard': Error restarting bundles
2016-11-13 20:57:10.872 [ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-package-standard': Error restarting bundles
-----
2016-11-13 20:53:35.704 [ERROR] [ps4j.pax.logging.pax-logging-service] - FrameworkEvent ERROR - org.ops4j.pax.logging.pax-logging-service
java.io.IOException: Exception in opening zip file: /share/CACHEDEV1_DATA/.qpkg/openHAB/distribution/userdata/cache/org.eclipse.osgi/6/0/bundleFile
-----
2016-11-13 20:53:51.197 [ERROR] [ps4j.pax.logging.pax-logging-service] - FrameworkEvent ERROR - org.ops4j.pax.logging.pax-logging-service
java.io.IOException: Exception in opening zip file: /share/CACHEDEV1_DATA/.qpkg/openHAB/distribution/userdata/cache/org.eclipse.osgi/6/0/bundleFile
        at org.eclipse.osgi.framework.util.SecureAction.getZipFile(SecureAction.java:305)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.storage.bundlefile.ZipBundleFile.basicOpen(ZipBundleFile.java:85)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.storage.bundlefile.ZipBundleFile.getZipFile(ZipBundleFile.java:98)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.storage.bundlefile.ZipBundleFile.checkedOpen(ZipBundleFile.java:65)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.storage.bundlefile.ZipBundleFile.getEntry(ZipBundleFile.java:232)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findClassImpl(ClasspathManager.java:562)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClassImpl(ClasspathManager.java:540)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:527)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:324)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:320)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:395)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:345)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:337)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)[:1.8.0_65]
        at java.lang.Class.forName0(Native Method)[:1.8.0_65]
        at java.lang.Class.forName(Class.java:264)[:1.8.0_65]
        at org.apache.log4j.OsgiThrowableRenderer.findClass(OsgiThrowableRenderer.java:226)[6:org.ops4j.pax.logging.pax-logging-service:1.8.5]
        at org.apache.log4j.OsgiThrowableRenderer.formatElement(OsgiThrowableRenderer.java:136)[6:org.ops4j.pax.logging.pax-logging-service:1.8.5]
        at org.apache.log4j.OsgiThrowableRenderer.doRender(OsgiThrowableRenderer.java:107)[6:org.ops4j.pax.logging.pax-logging-service:1.8.5]
        at org.apache.log4j.OsgiThrowableRenderer.doRender(OsgiThrowableRenderer.java:52)[6:org.ops4j.pax.logging.pax-logging-service:1.8.5]
        at org.apache.log4j.spi.ThrowableInformation.getThrowableStrRep(ThrowableInformation.java:89)[6:org.ops4j.pax.logging.pax-logging-service:1.8.5]
        at org.apache.log4j.spi.LoggingEvent.getThrowableStrRep(LoggingEvent.java:413)[6:org.ops4j.pax.logging.pax-logging-service:1.8.5]
        at org.apache.log4j.WriterAppender.subAppend(WriterAppender.java:313)[6:org.ops4j.pax.logging.pax-logging-service:1.8.5]
        at org.apache.log4j.RollingFileAppender.subAppend(RollingFileAppender.java:276)[6:org.ops4j.pax.logging.pax-logging-service:1.8.5]
        at org.apache.log4j.WriterAppender.append(WriterAppender.java:162)[6:org.ops4j.pax.logging.pax-logging-service:1.8.5]
        at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:251)[6:org.ops4j.pax.logging.pax-logging-service:1.8.5]
        at org.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:59)[6:org.ops4j.pax.logging.pax-logging-service:1.8.5]
        at org.apache.log4j.Category.callAppenders(Category.java:179)[6:org.ops4j.pax.logging.pax-logging-service:1.8.5]
        at org.apache.log4j.Category.forcedLog(Category.java:333)[6:org.ops4j.pax.logging.pax-logging-service:1.8.5]
        at org.apache.log4j.Category.log(Category.java:724)[6:org.ops4j.pax.logging.pax-logging-service:1.8.5]
        at org.ops4j.pax.logging.service.internal.PaxLoggerImpl.error(PaxLoggerImpl.java:195)[6:org.ops4j.pax.logging.pax-logging-service:1.8.5]
        at org.ops4j.pax.logging.service.internal.PaxLoggingServiceImpl.log(PaxLoggingServiceImpl.java:161)[6:org.ops4j.pax.logging.pax-logging-service:1.8.5]
        at org.ops4j.pax.logging.service.internal.PaxLoggingServiceImpl.log(PaxLoggingServiceImpl.java:136)[6:org.ops4j.pax.logging.pax-logging-service:1.8.5]
        at org.ops4j.pax.logging.service.internal.FrameworkHandler.frameworkEvent(FrameworkHandler.java:137)[6:org.ops4j.pax.logging.pax-logging-service:1.8.5]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:926)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
Caused by: java.io.FileNotFoundException: /share/CACHEDEV1_DATA/.qpkg/openHAB/distribution/userdata/cache/org.eclipse.osgi/6/0/bundleFile (No such file or directory)
        at java.util.zip.ZipFile.open(Native Method)[:1.8.0_65]
        at java.util.zip.ZipFile.<init>(ZipFile.java:219)[:1.8.0_65]
        at java.util.zip.ZipFile.<init>(ZipFile.java:149)[:1.8.0_65]
        at java.util.zip.ZipFile.<init>(ZipFile.java:163)[:1.8.0_65]
        at org.eclipse.osgi.framework.util.SecureAction.getZipFile(SecureAction.java:288)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        ...

**Comment by CHF64** [comment]
Hi,
I am having the same issue as nodecentral. I running a TS-251.
Any help is much appreciated.

**Comment by thopiekar** [comment]
@nodecentral Well, I often see that message when openHAB is not ready aka not fully started.
Does that message appear always? Even when waiting eg. for 15 minutes?

**Comment by nodecentral** [comment]
hi @thopiekar - i have left it for hours, and now days but it still shows the same 404 error mentioned above..

**Comment by thopiekar** [comment]
Hmm, then there must be another problem.
Could you backup your modified script, remove openhab completly (while checking for any left files via SSH) and reinstall? After installation the service will be started automatically and will fail as you are using 8090 already. SSH again to your NAS, stop the service with the original script and replace it with ours after that. Reboot and look whether it is activated in the AppCenter.

It really should work at the end... I mean I even changed the port already to 8090 from 8080, which is originally used. I don't see a reason why switching so any other port should fail...

**Comment by nodecentral** [comment]
This was installed fresh - and checking the folder structure - [/share/CACHEDEV1_DATA/.qpkg/openHAB/distribution/conf] #
I cannot find a config script ? 

[/share/CACHEDEV1_DATA/.qpkg/openHAB/distribution/conf] # ls
html/        items/       rules/       services/    things/
icons/       persistence/ scripts/     sitemaps/    transform/

**Comment by oiskenny** [comment]
same problem :(
using a TVS-1282

**Comment by jlongton** [comment]
Similar problem with my TS-251+

2016-11-29 16:21:16.039 [ERROR] [.glassfish.hk2.osgi-resource-locator] - FrameworkEvent ERROR - org.glassfish.hk2.osgi-resource-locator
org.osgi.framework.BundleException: Exception in org.apache.karaf.features.internal.service.FeaturesServiceImpl$3.end()
	at org.eclipse.osgi.internal.framework.OSGiFrameworkHooks$CoreResolverHookFactory.handleHookException(OSGiFrameworkHooks.java:164)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
	at org.eclipse.osgi.internal.framework.OSGiFrameworkHooks$CoreResolverHookFactory$CoreResolverHook.end(OSGiFrameworkHooks.java:340)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
	at org.eclipse.osgi.container.ModuleResolver$ResolveProcess.resolve(ModuleResolver.java:901)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
	at org.eclipse.osgi.container.ModuleResolver.resolveDelta(ModuleResolver.java:111)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
	at org.eclipse.osgi.container.ModuleContainer.resolveAndApply(ModuleContainer.java:479)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
	at org.eclipse.osgi.container.ModuleContainer.resolve(ModuleContainer.java:437)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
	at org.eclipse.osgi.container.ModuleContainer.resolve(ModuleContainer.java:427)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
	at org.eclipse.osgi.container.Module.start(Module.java:416)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1498)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
2016-11-29 16:21:59.635 [INFO ] [assic.internal.servlet.WebAppServlet] - Started Classic UI at /classicui/app
2016-11-29 16:21:59.854 [INFO ] [.dashboard.internal.DashboardService] - Started dashboard at /start
2016-11-29 16:21:59.940 [INFO ] [arthome.ui.paper.internal.PaperUIApp] - Started Paper UI at /ui
2016-11-29 16:22:00.386 [INFO ] [basic.internal.servlet.WebAppServlet] - Started Basic UI at /basicui/app
2016-11-29 16:22:00.400 [INFO ] [core.karaf.internal.FeatureInstaller] - Installed 'openhab-package-standard'

**Comment by thopiekar** [comment]
@jlongton Thanks. So I guess you also didn't report that in the openHAB forums?

@kaikreuzer Do you have an idea why it happens here? More recent JRE needed here? :confused:

**Comment by jlongton** [comment]
@thopiekar I have not reported this in the openHAB forums.  I can though.  I figured I'd post the log contents to see if there was anything insightful.  It doesn't mean much to me.

**Comment by thopiekar** [comment]
@jlongton Same for me here. I just packaged openHAB for QNAP, but have no idea about the magic behind openHAB. If it was a bundle of Python software I could probably understand better what is happening here.
So yes, if you like add it to the forums or let's wait for an reply by @kaikreuzer.

**Comment by thopiekar** [comment]
If you like report it here. I have no idea why it happens. Only made these packages here, after I've got openHAB working on my NAS by installing by hand.
Haven't asked it around so far, but which Java versions are you using on your NASs? Recently there were problems with a binding, so I had to implement an own JRE downloader.

**Comment by dayjobtitus** [comment]
I ran into this same issue on fresh install and fixed it (not sure if coincidence so maybe its not fixed for all) by clicking on the down arrow next to OPEN under the app icon and clicking "display on" and selecting "everyones". It worked right after.

**Comment by thopiekar** [comment]
@jlongton , @nodecentral , @oiskenny : Can you confirm that this works?

**Comment by Confectrician** [comment]
I can confirm this (maybe) @thopiekar.
I just read this issue thread while having the same problem.

Now i have set the "display on" setting to everyone and after some minutes i was able to open the openHAB Page.
I will test the behaviour after changing that setting back to "admin only"

**Comment by thopiekar** [comment]
Thanks @Confectrician 

I'm looking forward to hear feedback on this from you. And thank you again for investing time :+1:

**Comment by nodecentral** [comment]
Hi @thopiekar 

Sadly changing the display options does not change anything for me, I still get the same 404 error. :(

**Comment by nodecentral** [comment]
interesting observation, i have just tried 2.0.0-b3-1 and that works, i do not get the 404 error ?!!

i had tried the latest one numerous times, and got that error !???

**Comment by Confectrician** [comment]
Hey @thopiekar,

I have OpenHab running with "admin only visibility" for some days now.
Seems that the setting doesnt affect anything for me and it was  just a coincidence.
Maybe i just had to wait some time and there was a time overlap while changig the setting?!

@nodecentral 
I was wondering about the place where the config file is stored too, meanwhile.
Did you find it yet?

**Comment by nodecentral** [comment]
Hi @confectrician 

I can only assume the approach is different with 2.0 - as I can add certain things via the UI (I'm using the Paper UI) and it was able to discover my Sonos and Hue lights. I assume it stores the devices it finds in the .jar files or something -   and then you have to use the separate/designated txt files for any manual things like Things, Bindings etc  (but i might be way off !!)

I tried to upgrade from b3 to b4 (install over the top) but it failed and seems to have removed the icon now from my screen - however I can still access it over port 8090.

I defiantly like the potential it's just not behaving well for me on my QNAP.

**Comment by thopiekar** [comment]
Try setting different ports: https://github.com/openhab/openhab-qnap-qpkg/issues/20#issuecomment-294470868
